### ISSUE TITLE
React Group Project

### ISSUE THREAD

**Issue by touredri** [mahabubx7/space-cars#25]
https://github.com/mahabubx7/space-cars/

- [x] We are only two members @mahabubx7 @touredri

**Comment by christianbiring1** [comment]
Hi @touredri @mahabubx7 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS; APPROVED :tada: 

## Highlights
- [ ] All tasks have been distributed equally :+1: 
- [ ] the tasks have been assigned correctly :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
